version: "3.8"

services:
  web:
    build: ./project
    ports:
      - 8004:8000
    command: uvicorn app:app --host 0.0.0.0 --reload
    volumes:
      - ./project:/usr/src/app
    environment:
      # - MQ_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      # - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      # - rabbitmq
      - db
      # - worker
      # - rqworker

  worker:
    build: ./project
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    environment:
      # - MQ_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      # - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      # - rabbitmq
      - db

  rqworker:
    build: ./project
    command: rq worker task_queue --url redis://redis:6379/0
    volumes:
      - ./project:/usr/src/app
    environment:
      # - MQ_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      # - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      # - web
      - redis
      # - rabbitmq
      - db

  redis:
    image: redis:7
    # hostname: redis
    ports:
      - "6379:6379"

  # rabbitmq:
  #   image: rabbitmq:3.12-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  # docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management

  dashboard:
    build: ./project
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    # command: celery --broker=amqp://guest:guest@rabbitmq:5672// flower --port=5555
    ports:
      - 5556:5555
    environment:
      # - MQ_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      # - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
      - db

  db:
    image: mongo:5.0.6
    hostname: mongodbserver
    environment:
      - HOME=/data/db
    volumes:
      # - /var/lib/mongodb:/data/db
      - E:\docker\volume_backups\mongodb:/data/db
    ports:
      - "27017:27017"
